[2022-05-25 01:40:28,110] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: TRAVELOKA_V1.crawl_data scheduled__2022-05-24T00:00:00+00:00 [queued]>
[2022-05-25 01:40:28,121] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: TRAVELOKA_V1.crawl_data scheduled__2022-05-24T00:00:00+00:00 [queued]>
[2022-05-25 01:40:28,121] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-05-25 01:40:28,121] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-05-25 01:40:28,121] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-05-25 01:40:28,181] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): crawl_data> on 2022-05-24 00:00:00+00:00
[2022-05-25 01:40:28,186] {standard_task_runner.py:52} INFO - Started process 122 to run task
[2022-05-25 01:40:28,192] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'TRAVELOKA_V1', 'crawl_data', 'scheduled__2022-05-24T00:00:00+00:00', '--job-id', '126', '--raw', '--subdir', 'DAGS_FOLDER/test/test.py', '--cfg-path', '/tmp/tmp4qe0bph_', '--error-file', '/tmp/tmpx21s_8_q']
[2022-05-25 01:40:28,193] {standard_task_runner.py:80} INFO - Job 126: Subtask crawl_data
[2022-05-25 01:40:28,411] {task_command.py:369} INFO - Running <TaskInstance: TRAVELOKA_V1.crawl_data scheduled__2022-05-24T00:00:00+00:00 [running]> on host 85e8df78351f
[2022-05-25 01:40:29,637] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=TRAVELOKA_V1
AIRFLOW_CTX_DAG_ID=TRAVELOKA_V1
AIRFLOW_CTX_TASK_ID=crawl_data
AIRFLOW_CTX_EXECUTION_DATE=2022-05-24T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-05-24T00:00:00+00:00
[2022-05-25 01:40:29,639] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-05-25 01:40:29,641] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'cd /opt/***/dags/test && scrapy crawl hotel']
[2022-05-25 01:40:29,660] {subprocess.py:85} INFO - Output:
[2022-05-25 01:40:39,646] {subprocess.py:92} INFO - /opt/***/dags/test/hotel/items.py:5: ScrapyDeprecationWarning: scrapy.loader.processors.TakeFirst is deprecated, instantiate itemloaders.processors.TakeFirst instead.
[2022-05-25 01:40:39,646] {subprocess.py:92} INFO -   hotel_name = scrapy.Field(output_processor=TakeFirst())
[2022-05-25 01:40:39,646] {subprocess.py:92} INFO - /opt/***/dags/test/hotel/items.py:6: ScrapyDeprecationWarning: scrapy.loader.processors.TakeFirst is deprecated, instantiate itemloaders.processors.TakeFirst instead.
[2022-05-25 01:40:39,646] {subprocess.py:92} INFO -   hotel_rating = scrapy.Field(output_processor=TakeFirst())
[2022-05-25 01:40:39,646] {subprocess.py:92} INFO - /opt/***/dags/test/hotel/items.py:7: ScrapyDeprecationWarning: scrapy.loader.processors.TakeFirst is deprecated, instantiate itemloaders.processors.TakeFirst instead.
[2022-05-25 01:40:39,646] {subprocess.py:92} INFO -   hotel_address = scrapy.Field(output_processor=TakeFirst())
[2022-05-25 01:40:39,646] {subprocess.py:92} INFO - /opt/***/dags/test/hotel/items.py:8: ScrapyDeprecationWarning: scrapy.loader.processors.TakeFirst is deprecated, instantiate itemloaders.processors.TakeFirst instead.
[2022-05-25 01:40:39,646] {subprocess.py:92} INFO -   hotel_point_review = scrapy.Field(output_processor=TakeFirst())
[2022-05-25 01:40:39,646] {subprocess.py:92} INFO - /opt/***/dags/test/hotel/items.py:9: ScrapyDeprecationWarning: scrapy.loader.processors.TakeFirst is deprecated, instantiate itemloaders.processors.TakeFirst instead.
[2022-05-25 01:40:39,647] {subprocess.py:92} INFO -   hotel_sum_review = scrapy.Field(output_processor=TakeFirst())
[2022-05-25 01:40:39,647] {subprocess.py:92} INFO - /opt/***/dags/test/hotel/items.py:10: ScrapyDeprecationWarning: scrapy.loader.processors.TakeFirst is deprecated, instantiate itemloaders.processors.TakeFirst instead.
[2022-05-25 01:40:39,647] {subprocess.py:92} INFO -   hotel_url = scrapy.Field(output_processor=TakeFirst())
[2022-05-25 01:40:39,700] {subprocess.py:92} INFO - Traceback (most recent call last):
[2022-05-25 01:40:39,701] {subprocess.py:92} INFO -   File "/home/***/.local/lib/python3.7/site-packages/mysql/connector/connection_cext.py", line 246, in _open_connection
[2022-05-25 01:40:39,701] {subprocess.py:92} INFO -     self._cmysql.connect(**cnx_kwargs)
[2022-05-25 01:40:39,701] {subprocess.py:92} INFO - _mysql_connector.MySQLInterfaceError: Lost connection to MySQL server at 'reading initial communication packet', system error: 0
[2022-05-25 01:40:39,701] {subprocess.py:92} INFO - 
[2022-05-25 01:40:39,701] {subprocess.py:92} INFO - During handling of the above exception, another exception occurred:
[2022-05-25 01:40:39,701] {subprocess.py:92} INFO - 
[2022-05-25 01:40:39,701] {subprocess.py:92} INFO - Traceback (most recent call last):
[2022-05-25 01:40:39,701] {subprocess.py:92} INFO -   File "/home/***/.local/bin/scrapy", line 8, in <module>
[2022-05-25 01:40:39,701] {subprocess.py:92} INFO -     sys.exit(execute())
[2022-05-25 01:40:39,701] {subprocess.py:92} INFO -   File "/home/***/.local/lib/python3.7/site-packages/scrapy/cmdline.py", line 144, in execute
[2022-05-25 01:40:39,701] {subprocess.py:92} INFO -     cmd.crawler_process = CrawlerProcess(settings)
[2022-05-25 01:40:39,702] {subprocess.py:92} INFO -   File "/home/***/.local/lib/python3.7/site-packages/scrapy/crawler.py", line 290, in __init__
[2022-05-25 01:40:39,702] {subprocess.py:92} INFO -     super().__init__(settings)
[2022-05-25 01:40:39,702] {subprocess.py:92} INFO -   File "/home/***/.local/lib/python3.7/site-packages/scrapy/crawler.py", line 167, in __init__
[2022-05-25 01:40:39,702] {subprocess.py:92} INFO -     self.spider_loader = self._get_spider_loader(settings)
[2022-05-25 01:40:39,702] {subprocess.py:92} INFO -   File "/home/***/.local/lib/python3.7/site-packages/scrapy/crawler.py", line 161, in _get_spider_loader
[2022-05-25 01:40:39,702] {subprocess.py:92} INFO -     return loader_cls.from_settings(settings.frozencopy())
[2022-05-25 01:40:39,702] {subprocess.py:92} INFO -   File "/home/***/.local/lib/python3.7/site-packages/scrapy/spiderloader.py", line 67, in from_settings
[2022-05-25 01:40:39,702] {subprocess.py:92} INFO -     return cls(settings)
[2022-05-25 01:40:39,702] {subprocess.py:92} INFO -   File "/home/***/.local/lib/python3.7/site-packages/scrapy/spiderloader.py", line 24, in __init__
[2022-05-25 01:40:39,702] {subprocess.py:92} INFO -     self._load_all_spiders()
[2022-05-25 01:40:39,702] {subprocess.py:92} INFO -   File "/home/***/.local/lib/python3.7/site-packages/scrapy/spiderloader.py", line 51, in _load_all_spiders
[2022-05-25 01:40:39,702] {subprocess.py:92} INFO -     for module in walk_modules(name):
[2022-05-25 01:40:39,702] {subprocess.py:92} INFO -   File "/home/***/.local/lib/python3.7/site-packages/scrapy/utils/misc.py", line 80, in walk_modules
[2022-05-25 01:40:39,702] {subprocess.py:92} INFO -     mod = import_module(path)
[2022-05-25 01:40:39,703] {subprocess.py:92} INFO -   File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
[2022-05-25 01:40:39,703] {subprocess.py:92} INFO -     return _bootstrap._gcd_import(name[level:], package, level)
[2022-05-25 01:40:39,703] {subprocess.py:92} INFO -   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
[2022-05-25 01:40:39,703] {subprocess.py:92} INFO -   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
[2022-05-25 01:40:39,703] {subprocess.py:92} INFO -   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
[2022-05-25 01:40:39,703] {subprocess.py:92} INFO -   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
[2022-05-25 01:40:39,703] {subprocess.py:92} INFO -   File "<frozen importlib._bootstrap_external>", line 728, in exec_module
[2022-05-25 01:40:39,703] {subprocess.py:92} INFO -   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
[2022-05-25 01:40:39,703] {subprocess.py:92} INFO -   File "/opt/***/dags/test/hotel/spiders/__init__.py", line 9, in <module>
[2022-05-25 01:40:39,703] {subprocess.py:92} INFO -     from hotel.check_DB import *
[2022-05-25 01:40:39,703] {subprocess.py:92} INFO -   File "/opt/***/dags/test/hotel/check_DB.py", line 22, in <module>
[2022-05-25 01:40:39,703] {subprocess.py:92} INFO -     database=MYSQL_DB
[2022-05-25 01:40:39,703] {subprocess.py:92} INFO -   File "/home/***/.local/lib/python3.7/site-packages/mysql/connector/__init__.py", line 272, in connect
[2022-05-25 01:40:39,703] {subprocess.py:92} INFO -     return CMySQLConnection(*args, **kwargs)
[2022-05-25 01:40:39,703] {subprocess.py:92} INFO -   File "/home/***/.local/lib/python3.7/site-packages/mysql/connector/connection_cext.py", line 94, in __init__
[2022-05-25 01:40:39,703] {subprocess.py:92} INFO -     self.connect(**kwargs)
[2022-05-25 01:40:39,704] {subprocess.py:92} INFO -   File "/home/***/.local/lib/python3.7/site-packages/mysql/connector/abstracts.py", line 1052, in connect
[2022-05-25 01:40:39,704] {subprocess.py:92} INFO -     self._open_connection()
[2022-05-25 01:40:39,704] {subprocess.py:92} INFO -   File "/home/***/.local/lib/python3.7/site-packages/mysql/connector/connection_cext.py", line 252, in _open_connection
[2022-05-25 01:40:39,704] {subprocess.py:92} INFO -     sqlstate=exc.sqlstate)
[2022-05-25 01:40:39,704] {subprocess.py:92} INFO - mysql.connector.errors.OperationalError: 2013 (HY000): Lost connection to MySQL server at 'reading initial communication packet', system error: 0
[2022-05-25 01:40:39,847] {subprocess.py:96} INFO - Command exited with return code 1
[2022-05-25 01:40:39,870] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2022-05-25 01:40:39,910] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=TRAVELOKA_V1, task_id=crawl_data, execution_date=20220524T000000, start_date=20220525T014028, end_date=20220525T014039
[2022-05-25 01:40:40,009] {standard_task_runner.py:97} ERROR - Failed to execute job 126 for task crawl_data (Bash command failed. The command returned a non-zero exit code 1.; 122)
[2022-05-25 01:40:40,053] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-05-25 01:40:42,091] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
